### ISSUE TITLE
IndexError: Invalid key: 0 is out of bounds for size 0

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine.py#23]
Here is the error from here: https://app.sil.hosted.allegro.ai/projects/*/experiments/aab980ec463e46ddaf5ec90f9c36d1ea/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=&deep=true

```
[INFO|trainer.py:565] 2023-08-09 04:47:43,644 >> max_steps is given, it will override any value given in num_train_epochs
[INFO|trainer.py:622] 2023-08-09 04:47:43,644 >> Using cuda_amp half precision backend
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.8/code/untitled.py", line 12, in <module>
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/machine/jobs/build_nmt_engine.py", line 56, in run
    job.run(check_canceled)
  File "/usr/local/lib/python3.8/dist-packages/machine/jobs/nmt_engine_build_job.py", line 52, in run
    model_trainer.train(check_canceled=check_canceled)
  File "/usr/local/lib/python3.8/dist-packages/machine/translation/huggingface/hugging_face_nmt_model_trainer.py", line 276, in train
    train_result = self._trainer.train(resume_from_checkpoint=ckpt)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1676, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 906, in get_train_dataloader
    train_sampler = self._get_train_sampler()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 828, in _get_train_sampler
    return LengthGroupedSampler(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer_pt_utils.py", line 571, in __init__
    not (isinstance(dataset[0], dict) or isinstance(dataset[0], BatchEncoding))
  File "/usr/local/lib/python3.8/dist-packages/datasets/arrow_dataset.py", line 2590, in __getitem__
    return self._getitem(
  File "/usr/local/lib/python3.8/dist-packages/datasets/arrow_dataset.py", line 2574, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/usr/local/lib/python3.8/dist-packages/datasets/formatting/formatting.py", line 588, in query_table
    _check_valid_index_key(key, size)
  File "/usr/local/lib/python3.8/dist-packages/datasets/formatting/formatting.py", line 531, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 0 is out of bounds for size 0
2023-08-09 04:47:52
Process failed, exit code 1
```

What is going on?

**Comment by johnml1135** [comment]
This is related to [#45](https://github.com/sillsdev/serval/issues/45).

**Comment by johnml1135** [comment]
I believe this should be resolved now - if there are no pairs, there will be no training.

**Comment by pmachapman** [comment]
Has this change been deployed to QA? I am still getting the error when I have a source text but the target is empty (both are in the NLLB):
```json
[
  {
    "id": "652dd146dc41e7f57f8e36c9",
    "url": "/api/v1/translation/engines/652dd13ddc41e7f57f8e36b1/builds/652dd146dc41e7f57f8e36c9",
    "revision": 5,
    "engine": {
      "id": "652dd13ddc41e7f57f8e36b1",
      "url": "/api/v1/translation/engines/652dd13ddc41e7f57f8e36b1"
    },
    "pretranslate": [
      {
        "corpus": {
          "id": "652dd146dc41e7f57f8e36c8",
          "url": "/api/v1/translation/engines/652dd13ddc41e7f57f8e36b1/corpora/652dd146dc41e7f57f8e36c8"
        }
      }
    ],
    "step": 0,
    "percentCompleted": 0,
    "message": "IndexError : Invalid key: 0 is out of bounds for size 0",
    "queueDepth": 0,
    "state": "Faulted",
    "dateFinished": "2023-10-17T00:12:52.76Z",
    "options": "{}"
  }
]
```

**Comment by johnml1135** [comment]
This is still happening - 
```
SIL.Machine.AspNetCore.Services.ClearMLMonitorService[0]\n Build faulted (652dcfabdc41e7f57f8e369a). Error: IndexError : Invalid key: 0 is out of bounds for size 0\n"
```

What should we do if there is truly no data?  We should probably throw an error in machine.

**Comment by Enkidu93** [comment]
(I can't find the project in ClearML - could you send a link so I can see the whole stack trace). 

Are these two separate issues though?

1. If there's just source text and the languages are in NLLB's 200, we should be able to inference - not fail.
2. if there is truly no data - neither source nor target - we should catch it and throw a more meaningful error.

Issue 1 has to be handled in machine.py, not Machine. Issue 2 could be handled in either place potentially. I think we could use the corpus size parameter (?) if we went the Machine route. We could also just throw (or catch and throw) an error in machine.py that's more descriptive.  Thoughts @johnml1135 ? I'm not set up to develop in machine.py at the moment regardless, but I could take care of issue 2 if you like.

**Comment by johnml1135** [comment]
(1) is already covered.  Let's just do (2) in Machine directly and throw if there is no data.

**Comment by johnml1135** [comment]
Correction:
(1) is not working - source and no target is causing a crash
(2) Machine should directly fail.

**Comment by mshannon-sil** [comment]
I just tested the source and no target scenario with some toy data, and it's skipping training like it's supposed to for me. @johnml1135 are the files for the build job from that experiment saved anywhere in the S3 bucket so I can see what the directory looks like? I know we were all operating under the belief that Machine always creates a train.src.txt and train.trg.txt even if no data is supplied, but I'd like to verify that since missing those files would cause machine.py to crash.

**Comment by mshannon-sil** [comment]
Actually if it's getting to training then it's downloading train.src.txt and train.trg.txt fine. I'd still like to see the contents of those files though if possible.

**Comment by pmachapman** [comment]
I have attached the data our testers used to initially produce the error. The project is the ASV (English) and the target is in the language Kannada (both are in the NLLB).

[bss1.zip](https://github.com/sillsdev/machine.py/files/13034502/bss1.zip)

**Comment by mshannon-sil** [comment]
I ran Serval using the first English source file and the first Kannada target file, and I'm not getting any errors. So it seems that skipping training is working.

**Comment by ddaspit** [comment]
Maybe the corpus/build is not setup correctly in Serval. Can we take a look at the Serval engine and build docs in Mongo to see how they are configured?

**Comment by Enkidu93** [comment]
@mshannon-sil Do you want me to dig into this given that it seems like it might he an issue on the machine/serval side? I can look at the MongoDB and see if I can find the docs associated with their issue.

**Comment by mshannon-sil** [comment]
Yeah I'd appreciate it if you could take a look at that.

**Comment by Enkidu93** [comment]
> Yeah I'd appreciate it if you could take a look at that.

Sure! I'll take a peek either tonight or in the morning.

**Comment by Enkidu93** [comment]
I also tried running builds both with an empty target file (like the ones Peter sent) and with no target. Both worked properly. I imagine it's a set-up issue, but the I can't access Mongo right now for some reason. I'll keep trying throughout the day. @pmachapman, is there any chance you could share the procedure that was used to create this issue or the full data on the corpus, files, and engine (as well as the build you included above)?

**Comment by Enkidu93** [comment]
So @johnml1135 @ddaspit, as for the Machine side, when exactly would you like it to throw an error - both when the source is empty and when there is no source? Now, what we can't do is return such an error when the source and target are empty but are using user-defined refs because they'll just be interpreted as lines of content (if there are no tabs at the end of each line), but otherwise, that should be doable. I'm just wondering how useful throwing this error will be. And when it comes to not having any source files whatsoever, wouldn't it be cleaner to let Serval handle that? At the moment, no such errors are thrown - as far as I can tell by testing.

**Comment by johnml1135** [comment]
Machine can check for 2 things:
* throw an [ArgumentException](http://msdn.microsoft.com/en-us/library/system.argumentexception(loband).aspx) if there are no source files
* throw an [ArgumentException](http://msdn.microsoft.com/en-us/library/system.argumentexception(loband).aspx) if all source files have no data (there are no valid lines in any of them).  It is ok if some source files have no data.

**Comment by ddaspit** [comment]
Serval should return a 400 status code when a corpus is added with no source files.

**Comment by ddaspit** [comment]
The following line of code should determine if there are any non-empty source segments in the corpora passed to a build:

```cs
bool hasSourceSegments = corpora.Any(c => _corpusService.CreateTextCorpus(c.SourceFiles).Count(includeEmpty: false) > 0);
```

**Comment by Enkidu93** [comment]
Update: I've inadvertently recreated this issue yielding the same error message SF got. Checking it out now.

**Comment by Enkidu93** [comment]
Alrighty, so there was one particular pair of files in the data Peter gave us that seem to be causing the issue:
* [52_5.txt](https://github.com/sillsdev/machine.py/files/13057642/52_5.txt)
* [52_5.txt](https://github.com/sillsdev/machine.py/files/13057644/52_5.txt)
@ddaspit, do you see anything particularly odd about these files that might be causing the issue? Also, side question: Where exactly is the code that's throwing the error message? Is it in some library? It doesn't seem to be machine.py code.

**Comment by ddaspit** [comment]
I figured out what is going on. There is a bug in the `count` method. I will submit a PR to fix it.

**Comment by johnml1135** [comment]
So my understanding is:
* `missing_rows_allowed` was never used and could be safely discarded
* `count` did not account for lines with verse references but no actual text

Is that correct?
